
apiVersion: v1
kind: Pod
metadata:
  name: client5
spec:
  containers:
  - name: fedrelax-container-client
    image: quynhhgoogoo/fed-relax-client:latest
    volumeMounts:
    - mountPath: /app/data
      name: volume5
  volumes:
  - name: volume5
    persistentVolumeClaim:
      claimName: pvc-volume5
