
apiVersion: v1
kind: Pod
metadata:
  name: client1
spec:
  containers:
  - name: fedrelax-container-client
    image: quynhhgoogoo/fed-relax-client:latest
    volumeMounts:
    - mountPath: /app/data
      name: volume1
  volumes:
  - name: volume1
    persistentVolumeClaim:
      claimName: pvc-volume1
