
apiVersion: v1
kind: Pod
metadata:
  name: client1
spec:
  containers:
  - name: client1-container
    image: quynhhgoogoo/fed-relax-client:latest
    volumeMounts:
    - mountPath: /app/data
      name: volume1
  volumes:
  - name: volume1
    hostPath:
      path: /var/lib/docker/volumes/volume1/_data
      type: Directory
