
apiVersion: v1
kind: Pod
metadata:
  name: client2
spec:
  containers:
  - name: fedrelax-container-client
    image: quynhhgoogoo/fed-relax-client:latest
    volumeMounts:
    - mountPath: /app/data
      name: volume2
  volumes:
  - name: volume2
    persistentVolumeClaim:
      claimName: pvc-volume2
