apiVersion: apps/v1
kind: Deployment
metadata:
  name: fedrelax-deployment-server
  namespace: fed-relax
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fedrelax-server
  template:
    metadata:
      labels:
        app: fedrelax-server
    spec:
      restartPolicy: Always
      containers:
      - name: fedrelax-container-server
        image: quynhhgoogoo/fed-relax-server:latest
        command: ["python3", "-u", "/app/server/send.py"]
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: regcred

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fedrelax-deployment-client
  namespace: fed-relax
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fedrelax-client
  template:
    metadata:
      labels:
        app: fedrelax-client
    spec:
      restartPolicy: Always
      containers:
      - name: fedrelax-container-client
        image: quynhhgoogoo/fed-relax-client:latest
        command: ["python3", "-u", "/app/client/receive.py"]
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: regcred