apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: fed-relax
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fedrelax-server
  template:
    metadata:
      labels:
        app: fedrelax-server
    spec:
      serviceAccountName: my-service-account
      restartPolicy: Always
      containers:
      - name: fedrelax-container-server
        image: quynhhgoogoo/fed-relax-server:latest
        command: ["python3", "-u", "/app/server/server.py"]
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: regcred

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: fed-relax
spec:
  replicas: 20
  selector:
    matchLabels:
      app: fedrelax-client
  template:
    metadata:
      labels:
        app: fedrelax-client
    spec:
      restartPolicy: Always
      serviceAccountName: my-service-account
      containers:
      - name: fedrelax-container-client
        image: quynhhgoogoo/fed-relax-client:latest
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        command: ["python3", "-u", "/app/client/test.py"]
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: regcred