apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: fed-relax
subjects:
- kind: ServiceAccount
  name: default
  namespace: fed-relax
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
