# service1
apiVersion: v1
kind: Service
metadata:
  name: service1
  namespace: fed-relax
spec:
  selector:
    app: fedrelax
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---

# service2
apiVersion: v1
kind: Service
metadata:
  name: service2
  namespace: fed-relax
spec:
  selector:
    app: fedrelax
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
