# service1
apiVersion: v1
kind: Service
metadata:
  name: service1
  namespace: fed-relax
spec:
  selector:
    app: fed-relax-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
