apiVersion: v1
kind: Pod
metadata:
  name: test-pod-1
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    command: ["sleep", "3600"]


apiVersion: v1
kind: Pod
metadata:
  name: test-pod-2
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    command: ["sleep", "3600"]
