apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: processor
  namespace: fed-relax
spec:
  selector:
    matchLabels:
      app: fedrelax-client
  serviceName: "processor-service"
  replicas: 20
  template:
    metadata:
      labels:
        app: fedrelax-client
    spec:
      containers:
      - name: fedrelax-container-client
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name        
        image: quynhhgoogoo/fed-relax-client:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 4000
        volumeMounts:
        - name: input-data
          mountPath: /pod-data
          subPathExpr: $(MY_POD_NAME)
      volumes:
      - name: input-data
        hostPath:
          path: /data/input-data-inside-pod

# verify mounts
# kind create cluster --config 1m.3w.config 
# for i in {0..30};do kubectl exec -it processor-$i -- bash -c "hostname; ls /pod-data";done