apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: client
  namespace: fed-relax
spec:
  serviceName: "client"
  replicas: 5
  selector:
    matchLabels:
      app: fedrelax-client
  template:
    metadata:
      labels:
        app: fedrelax-client
    spec:
      serviceAccountName: my-service-account
      containers:
      - name: fedrelax-container-client
        image: quynhhgoogoo/fed-relax-client:latest
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        command: ["python3", "-u", "/app/load_data.py"]
        volumeMounts:
        - name: data-volume
          mountPath: /data
      initContainers:
      - name: init-create-dir
        image: busybox
        command: ['sh', '-c', 'mkdir -p /data/partition-${POD_NAME##*-}']
        volumeMounts:
        - name: data-volume
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data-volume
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
      storageClassName: standard
