apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: processor
  namespace: fed-relax
spec:
  selector:
    matchLabels:
      app: fedrelax-client # has to match .spec.template.metadata.labels
  serviceName: "fedrelax-client"
  replicas: 10 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: fedrelax-client # has to match .spec.selector.matchLabels
    spec:
      volumes:
      - name: input-data
        hostPath:
          path: /data/input-data-inside-pod
      terminationGracePeriodSeconds: 10
      containers:
      - name: fedrelax-container-client
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name        
        image: quynhhgoogoo/fed-relax-client:latest
        volumeMounts:
        - name: input-data
          mountPath: /pod-data
          subPathExpr: $(MY_POD_NAME)

# verify mounts
# kind create cluster --config 1m.3w.config 
# for i in {0..30};do kubectl exec -it processor-$i -- bash -c "hostname; ls /pod-data";done
