apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: fed-relax
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fedrelax-server
  template:
    metadata:
      labels:
        app: fedrelax-server
    spec:
      serviceAccountName: my-service-account
      restartPolicy: Always
      containers:
      - name: fedrelax-container-server
        image: quynhhgoogoo/fed-relax-server:latest
        command: ["python3", "-u", "/app/server/server.py"]
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: regcred
      