apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-reader-binding
  namespace: fed-relax
subjects:
- kind: ServiceAccount
  name: my-service-account  # Replace with the name of your service account
roleRef:
  kind: Role
  name: job-reader
  apiGroup: rbac.authorization.k8s.io
