apiVersion: v1
kind: Service
metadata:
  name: processor-service
  namespace: fed-relax
spec:
  clusterIP: None
  selector:
    app: fedrelax-client
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000

# processor-0.processor-service.fed-relax.svc.cluster.local
