apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: fed-relax
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["pods/status"]
  verbs: ["get"]
